apiVersion: v1
clusters:
- cluster:
    certificate-authority: ../.minikube_service/ca.crt
    server: http://127.0.0.1:37736
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: ../.minikube_service/client.crt
    client-key: ../.minikube_service/client.key